package org.apache.commons.imaging.formats.tiff.constants;

import androidx.exifinterface.media.ExifInterface;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfo;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoAscii;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoByte;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoBytes;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoDirectory;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoDouble;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoGpsText;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoLongs;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoRationals;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoSLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoSRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShort;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShortOrLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShorts;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoUndefined;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoUndefineds;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoUnknowns;

/* loaded from: classes2.dex */
public final class ExifTagConstants {
    public static final List<TagInfo> ALL_EXIF_TAGS;
    public static final int CONTRAST_1_VALUE_HIGH = 2;
    public static final int CONTRAST_1_VALUE_LOW = 1;
    public static final int CONTRAST_1_VALUE_NORMAL = 0;
    public static final int CUSTOM_RENDERED_VALUE_CUSTOM = 1;
    public static final int CUSTOM_RENDERED_VALUE_NORMAL = 0;
    public static final TagInfoLong EXIF_TAG_AFCP_IPTC;
    public static final TagInfoUnknowns EXIF_TAG_ANNOTATIONS;
    public static final TagInfoRational EXIF_TAG_APERTURE_VALUE;
    public static final TagInfoBytes EXIF_TAG_APPLICATION_NOTES;
    public static final TagInfoByte EXIF_TAG_BACKGROUND_COLOR_INDICATOR;
    public static final TagInfoBytes EXIF_TAG_BACKGROUND_COLOR_VALUE;
    public static final TagInfoShort EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH;
    public static final TagInfoShort EXIF_TAG_BITS_PER_RUN_LENGTH;
    public static final TagInfoAscii EXIF_TAG_BODY_SERIAL_NUMBER;
    public static final TagInfoAscii EXIF_TAG_BRIGHTNESS;
    public static final TagInfoSRational EXIF_TAG_BRIGHTNESS_VALUE;
    public static final TagInfoAscii EXIF_TAG_CAMERA_OWNER_NAME;
    public static final TagInfoUndefineds EXIF_TAG_CFAPATTERN;
    public static final TagInfoAscii EXIF_TAG_COLOR_CHARACTERIZATION;
    public static final TagInfoAscii EXIF_TAG_COLOR_SEQUENCE;
    public static final TagInfoBytes EXIF_TAG_COLOR_TABLE;
    public static final TagInfoUndefineds EXIF_TAG_COMPONENTS_CONFIGURATION;
    public static final TagInfoRational EXIF_TAG_COMPRESSED_BITS_PER_PIXEL;
    public static final TagInfoShort EXIF_TAG_CONTRAST_1;
    public static final TagInfoAscii EXIF_TAG_CONTRAST_2;
    public static final TagInfoAscii EXIF_TAG_CONVERTER;
    public static final TagInfoShort EXIF_TAG_CUSTOM_RENDERED;
    public static final TagInfoUnknowns EXIF_TAG_DATA_TYPE;
    public static final TagInfoAscii EXIF_TAG_DATE_TIME_DIGITIZED;
    public static final TagInfoAscii EXIF_TAG_DATE_TIME_ORIGINAL;
    public static final TagInfoUndefineds EXIF_TAG_DEVICE_SETTING_DESCRIPTION;
    public static final TagInfoRational EXIF_TAG_DIGITAL_ZOOM_RATIO;
    public static final TagInfoShort EXIF_TAG_EXIF_IMAGE_LENGTH;
    public static final TagInfoShort EXIF_TAG_EXIF_IMAGE_WIDTH;
    public static final TagInfoDirectory EXIF_TAG_EXIF_OFFSET;
    public static final TagInfoUndefineds EXIF_TAG_EXIF_VERSION;
    public static final TagInfoAscii EXIF_TAG_EXPOSURE;
    public static final TagInfoSRational EXIF_TAG_EXPOSURE_COMPENSATION;
    public static final TagInfoRational EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD;
    public static final TagInfoShort EXIF_TAG_EXPOSURE_MODE;
    public static final TagInfoShort EXIF_TAG_EXPOSURE_PROGRAM;
    public static final TagInfoRationals EXIF_TAG_EXPOSURE_TIME;
    public static final TagInfoUndefined EXIF_TAG_FILE_SOURCE;
    public static final TagInfoShort EXIF_TAG_FLASH;
    public static final TagInfoUndefineds EXIF_TAG_FLASHPIX_VERSION;
    public static final TagInfoRationals EXIF_TAG_FLASH_ENERGY_EXIF_IFD;
    public static final TagInfoRationals EXIF_TAG_FNUMBER;
    public static final TagInfoRationals EXIF_TAG_FOCAL_LENGTH;
    public static final TagInfoShort EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT;
    public static final TagInfoShort EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD;
    public static final TagInfoRational EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD;
    public static final TagInfoRational EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD;
    public static final TagInfoShort EXIF_TAG_GAIN_CONTROL;
    public static final TagInfoRational EXIF_TAG_GAMMA;
    public static final TagInfoDirectory EXIF_TAG_GPSINFO;
    public static final TagInfoShortOrLong EXIF_TAG_HCUSAGE;
    public static final TagInfoByte EXIF_TAG_IMAGE_COLOR_INDICATOR;
    public static final TagInfoBytes EXIF_TAG_IMAGE_COLOR_VALUE;
    public static final TagInfoUnknowns EXIF_TAG_IMAGE_DEPTH;
    public static final TagInfoUnknowns EXIF_TAG_IMAGE_HISTORY;
    public static final TagInfoUnknowns EXIF_TAG_IMAGE_NUMBER;
    public static final TagInfoAscii EXIF_TAG_IMAGE_UNIQUE_ID;
    public static final TagInfoLongs EXIF_TAG_INTERGRAPH_FLAG_REGISTERS;
    public static final TagInfoShorts EXIF_TAG_INTERGRAPH_PACKET_DATA;
    public static final TagInfoAscii EXIF_TAG_INTEROPERABILITY_INDEX;
    public static final TagInfoUndefined EXIF_TAG_INTEROPERABILITY_VERSION;
    public static final TagInfoDirectory EXIF_TAG_INTEROP_OFFSET;
    public static final TagInfoLong EXIF_TAG_IPTC_NAA;
    public static final TagInfoShorts EXIF_TAG_ISO;
    public static final TagInfoAscii EXIF_TAG_IT8HEADER;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_START_IFD2;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2;
    public static final TagInfoLong EXIF_TAG_LEAF_DATA;
    public static final TagInfoLong EXIF_TAG_LEAF_SUB_IFD;
    public static final TagInfoAscii EXIF_TAG_LENS;
    public static final TagInfoAscii EXIF_TAG_LENS_MAKE;
    public static final TagInfoAscii EXIF_TAG_LENS_MODEL;
    public static final TagInfoAscii EXIF_TAG_LENS_SERIAL_NUMBER;
    public static final TagInfoRationals EXIF_TAG_LENS_SPECIFICATION;
    public static final TagInfoShort EXIF_TAG_LIGHT_SOURCE;
    public static final TagInfoUndefineds EXIF_TAG_MAKER_NOTE;
    public static final TagInfoUnknowns EXIF_TAG_MATTEING;
    public static final TagInfoRational EXIF_TAG_MAX_APERTURE_VALUE;
    public static final TagInfoShort EXIF_TAG_METERING_MODE;
    public static final TagInfoUnknowns EXIF_TAG_MODEL_2;
    public static final TagInfoAscii EXIF_TAG_MOIRE_FILTER;
    public static final TagInfoUnknowns EXIF_TAG_NOISE_2;
    public static final TagInfoSLong EXIF_TAG_OFFSET_SCHEMA;
    public static final TagInfoUndefineds EXIF_TAG_OPTO_ELECTRIC_CONV_FACTOR;
    public static final TagInfoLong EXIF_TAG_OTHER_IMAGE_LENGTH;
    public static final TagInfoLong EXIF_TAG_OTHER_IMAGE_START;
    public static final TagInfoAscii EXIF_TAG_OWNER_NAME;
    public static final TagInfoBytes EXIF_TAG_PHOTOSHOP_SETTINGS;
    public static final TagInfoBytes EXIF_TAG_PIXEL_INTENSITY_RANGE;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_START_IFD0;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1;
    public static final TagInfoUndefined EXIF_TAG_PRINT_IM;
    public static final TagInfoAscii EXIF_TAG_PROCESSING_SOFTWARE;
    public static final TagInfoShort EXIF_TAG_RASTER_PADDING;
    public static final TagInfoAscii EXIF_TAG_RAW_FILE;
    public static final TagInfoAscii EXIF_TAG_RELATED_SOUND_FILE;
    public static final TagInfoShort EXIF_TAG_SATURATION_1;
    public static final TagInfoAscii EXIF_TAG_SATURATION_2;
    public static final TagInfoShort EXIF_TAG_SCENE_CAPTURE_TYPE;
    public static final TagInfoUndefined EXIF_TAG_SCENE_TYPE;
    public static final TagInfoUnknowns EXIF_TAG_SECURITY_CLASSIFICATION;
    public static final TagInfoAscii EXIF_TAG_SEMINFO;
    public static final TagInfoShort EXIF_TAG_SENSING_METHOD_EXIF_IFD;
    public static final TagInfoAscii EXIF_TAG_SERIAL_NUMBER;
    public static final TagInfoAscii EXIF_TAG_SHADOWS;
    public static final TagInfoShort EXIF_TAG_SHARPNESS_1;
    public static final TagInfoAscii EXIF_TAG_SHARPNESS_2;
    public static final TagInfoSRational EXIF_TAG_SHUTTER_SPEED_VALUE;
    public static final TagInfoAscii EXIF_TAG_SITE;
    public static final TagInfoAscii EXIF_TAG_SMOOTHNESS;
    public static final TagInfoAscii EXIF_TAG_SOFTWARE;
    public static final TagInfoUndefineds EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2;
    public static final TagInfoAscii EXIF_TAG_SPECTRAL_SENSITIVITY;
    public static final TagInfoDouble EXIF_TAG_STO_NITS;
    public static final TagInfoShorts EXIF_TAG_SUBJECT_AREA;
    public static final TagInfoRationals EXIF_TAG_SUBJECT_DISTANCE;
    public static final TagInfoShort EXIF_TAG_SUBJECT_DISTANCE_RANGE;
    public static final TagInfoShorts EXIF_TAG_SUBJECT_LOCATION;
    public static final TagInfoAscii EXIF_TAG_SUB_SEC_TIME;
    public static final TagInfoAscii EXIF_TAG_SUB_SEC_TIME_DIGITIZED;
    public static final TagInfoAscii EXIF_TAG_SUB_SEC_TIME_ORIGINAL;
    public static final TagInfoUnknowns EXIF_TAG_TIFF_EPSTANDARD_ID_2;
    public static final TagInfoUnknowns EXIF_TAG_TILE_DEPTH;
    public static final TagInfoByte EXIF_TAG_TRANSPARENCY_INDICATOR;
    public static final TagInfoGpsText EXIF_TAG_USER_COMMENT;
    public static final TagInfoShort EXIF_TAG_WHITE_BALANCE_1;
    public static final TagInfoAscii EXIF_TAG_WHITE_BALANCE_2;
    public static final int EXPOSURE_MODE_VALUE_AUTO = 0;
    public static final int EXPOSURE_MODE_VALUE_AUTO_BRACKET = 2;
    public static final int EXPOSURE_MODE_VALUE_MANUAL = 1;
    public static final int EXPOSURE_PROGRAM_VALUE_ACTION_HIGH_SPEED = 6;
    public static final int EXPOSURE_PROGRAM_VALUE_APERTURE_PRIORITY_AE = 3;
    public static final int EXPOSURE_PROGRAM_VALUE_CREATIVE_SLOW_SPEED = 5;
    public static final int EXPOSURE_PROGRAM_VALUE_LANDSCAPE = 8;
    public static final int EXPOSURE_PROGRAM_VALUE_MANUAL = 1;
    public static final int EXPOSURE_PROGRAM_VALUE_PORTRAIT = 7;
    public static final int EXPOSURE_PROGRAM_VALUE_PROGRAM_AE = 2;
    public static final int EXPOSURE_PROGRAM_VALUE_SHUTTER_SPEED_PRIORITY_AE = 4;
    public static final int FILE_SOURCE_VALUE_DIGITAL_CAMERA = 3;
    public static final int FILE_SOURCE_VALUE_FILM_SCANNER = 1;
    public static final int FILE_SOURCE_VALUE_REFLECTION_PRINT_SCANNER = 2;
    public static final int FLASH_VALUE_AUTO_DID_NOT_FIRE = 24;
    public static final int FLASH_VALUE_AUTO_DID_NOT_FIRE_RED_EYE_REDUCTION = 88;
    public static final int FLASH_VALUE_AUTO_FIRED = 25;
    public static final int FLASH_VALUE_AUTO_FIRED_RED_EYE_REDUCTION = 89;
    public static final int FLASH_VALUE_AUTO_FIRED_RED_EYE_REDUCTION_RETURN_DETECTED = 95;
    public static final int FLASH_VALUE_AUTO_FIRED_RED_EYE_REDUCTION_RETURN_NOT_DETECTED = 93;
    public static final int FLASH_VALUE_AUTO_FIRED_RETURN_DETECTED = 31;
    public static final int FLASH_VALUE_AUTO_FIRED_RETURN_NOT_DETECTED = 29;
    public static final int FLASH_VALUE_FIRED = 1;
    public static final int FLASH_VALUE_FIRED_RED_EYE_REDUCTION = 65;
    public static final int FLASH_VALUE_FIRED_RED_EYE_REDUCTION_RETURN_DETECTED = 71;
    public static final int FLASH_VALUE_FIRED_RED_EYE_REDUCTION_RETURN_NOT_DETECTED = 69;
    public static final int FLASH_VALUE_FIRED_RETURN_DETECTED = 7;
    public static final int FLASH_VALUE_FIRED_RETURN_NOT_DETECTED = 5;
    public static final int FLASH_VALUE_NO_FLASH = 0;
    public static final int FLASH_VALUE_NO_FLASH_FUNCTION = 32;
    public static final int FLASH_VALUE_OFF = 16;
    public static final int FLASH_VALUE_OFF_DID_NOT_FIRE_RETURN_NOT_DETECTED = 20;
    public static final int FLASH_VALUE_OFF_NO_FLASH_FUNCTION = 48;
    public static final int FLASH_VALUE_OFF_RED_EYE_REDUCTION = 80;
    public static final int FLASH_VALUE_ON = 9;
    public static final int FLASH_VALUE_ON_DID_NOT_FIRE = 8;
    public static final int FLASH_VALUE_ON_RED_EYE_REDUCTION = 73;
    public static final int FLASH_VALUE_ON_RED_EYE_REDUCTION_RETURN_DETECTED = 79;
    public static final int FLASH_VALUE_ON_RED_EYE_REDUCTION_RETURN_NOT_DETECTED = 77;
    public static final int FLASH_VALUE_ON_RETURN_DETECTED = 15;
    public static final int FLASH_VALUE_ON_RETURN_NOT_DETECTED = 13;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_CM = 3;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_INCHES = 2;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_MM = 4;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_NONE = 1;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_UM = 5;
    public static final int GAIN_CONTROL_VALUE_HIGH_GAIN_DOWN = 4;
    public static final int GAIN_CONTROL_VALUE_HIGH_GAIN_UP = 2;
    public static final int GAIN_CONTROL_VALUE_LOW_GAIN_DOWN = 3;
    public static final int GAIN_CONTROL_VALUE_LOW_GAIN_UP = 1;
    public static final int GAIN_CONTROL_VALUE_NONE = 0;
    public static final int LIGHT_SOURCE_VALUE_CLOUDY = 10;
    public static final int LIGHT_SOURCE_VALUE_COOL_WHITE_FLUORESCENT = 14;
    public static final int LIGHT_SOURCE_VALUE_D50 = 23;
    public static final int LIGHT_SOURCE_VALUE_D55 = 20;
    public static final int LIGHT_SOURCE_VALUE_D65 = 21;
    public static final int LIGHT_SOURCE_VALUE_D75 = 22;
    public static final int LIGHT_SOURCE_VALUE_DAYLIGHT = 1;
    public static final int LIGHT_SOURCE_VALUE_DAYLIGHT_FLUORESCENT = 12;
    public static final int LIGHT_SOURCE_VALUE_DAY_WHITE_FLUORESCENT = 13;
    public static final int LIGHT_SOURCE_VALUE_FINE_WEATHER = 9;
    public static final int LIGHT_SOURCE_VALUE_FLASH = 4;
    public static final int LIGHT_SOURCE_VALUE_FLUORESCENT = 2;
    public static final int LIGHT_SOURCE_VALUE_ISO_STUDIO_TUNGSTEN = 24;
    public static final int LIGHT_SOURCE_VALUE_OTHER = 255;
    public static final int LIGHT_SOURCE_VALUE_SHADE = 11;
    public static final int LIGHT_SOURCE_VALUE_STANDARD_LIGHT_A = 17;
    public static final int LIGHT_SOURCE_VALUE_STANDARD_LIGHT_B = 18;
    public static final int LIGHT_SOURCE_VALUE_STANDARD_LIGHT_C = 19;
    public static final int LIGHT_SOURCE_VALUE_TUNGSTEN = 3;
    public static final int LIGHT_SOURCE_VALUE_WHITE_FLUORESCENT = 15;
    public static final int METERING_MODE_VALUE_AVERAGE = 1;
    public static final int METERING_MODE_VALUE_CENTER_WEIGHTED_AVERAGE = 2;
    public static final int METERING_MODE_VALUE_MULTI_SEGMENT = 5;
    public static final int METERING_MODE_VALUE_MULTI_SPOT = 4;
    public static final int METERING_MODE_VALUE_OTHER = 255;
    public static final int METERING_MODE_VALUE_PARTIAL = 6;
    public static final int METERING_MODE_VALUE_SPOT = 3;
    public static final int SATURATION_1_VALUE_HIGH = 2;
    public static final int SATURATION_1_VALUE_LOW = 1;
    public static final int SATURATION_1_VALUE_NORMAL = 0;
    public static final int SCENE_CAPTURE_TYPE_VALUE_LANDSCAPE = 1;
    public static final int SCENE_CAPTURE_TYPE_VALUE_NIGHT = 3;
    public static final int SCENE_CAPTURE_TYPE_VALUE_PORTRAIT = 2;
    public static final int SCENE_CAPTURE_TYPE_VALUE_STANDARD = 0;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_COLOR_SEQUENTIAL_AREA = 5;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_COLOR_SEQUENTIAL_LINEAR = 8;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_NOT_DEFINED = 1;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_ONE_CHIP_COLOR_AREA = 2;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_THREE_CHIP_COLOR_AREA = 4;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_TRILINEAR = 7;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_TWO_CHIP_COLOR_AREA = 3;
    public static final int SHARPNESS_1_VALUE_HARD = 2;
    public static final int SHARPNESS_1_VALUE_NORMAL = 0;
    public static final int SHARPNESS_1_VALUE_SOFT = 1;
    public static final int SUBJECT_DISTANCE_RANGE_VALUE_CLOSE = 2;
    public static final int SUBJECT_DISTANCE_RANGE_VALUE_DISTANT = 3;
    public static final int SUBJECT_DISTANCE_RANGE_VALUE_MACRO = 1;
    public static final int WHITE_BALANCE_1_VALUE_AUTO = 0;
    public static final int WHITE_BALANCE_1_VALUE_MANUAL = 1;

    static {
        TagInfoAscii tagInfoAscii = new TagInfoAscii(ExifInterface.TAG_INTEROPERABILITY_INDEX, 1, -1, TiffDirectoryType.EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_INTEROPERABILITY_INDEX = tagInfoAscii;
        TagInfoUndefined tagInfoUndefined = new TagInfoUndefined("InteroperabilityVersion", 2, TiffDirectoryType.EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_INTEROPERABILITY_VERSION = tagInfoUndefined;
        TagInfoAscii tagInfoAscii2 = new TagInfoAscii("ProcessingSoftware", 11, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PROCESSING_SOFTWARE = tagInfoAscii2;
        TagInfoAscii tagInfoAscii3 = new TagInfoAscii("Software", 305, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SOFTWARE = tagInfoAscii3;
        TagInfoLong tagInfoLong = new TagInfoLong(ExifInterface.TAG_ORF_PREVIEW_IMAGE_START, 273, TiffDirectoryType.EXIF_DIRECTORY_IFD0, true);
        EXIF_TAG_PREVIEW_IMAGE_START_IFD0 = tagInfoLong;
        TagInfoLong tagInfoLong2 = new TagInfoLong(ExifInterface.TAG_ORF_PREVIEW_IMAGE_START, 273, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD1, true);
        EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1 = tagInfoLong2;
        TagInfoLong tagInfoLong3 = new TagInfoLong("JpgFromRawStart", 273, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD2, true);
        EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2 = tagInfoLong3;
        TagInfoLong tagInfoLong4 = new TagInfoLong(ExifInterface.TAG_ORF_PREVIEW_IMAGE_LENGTH, 279, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0 = tagInfoLong4;
        TagInfoLong tagInfoLong5 = new TagInfoLong(ExifInterface.TAG_ORF_PREVIEW_IMAGE_LENGTH, 279, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD1);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1 = tagInfoLong5;
        TagInfoLong tagInfoLong6 = new TagInfoLong("JpgFromRawLength", 279, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD2);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2 = tagInfoLong6;
        TagInfoLong tagInfoLong7 = new TagInfoLong(ExifInterface.TAG_ORF_PREVIEW_IMAGE_START, 513, TiffDirectoryType.EXIF_DIRECTORY_MAKER_NOTES);
        EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES = tagInfoLong7;
        TagInfoLong tagInfoLong8 = new TagInfoLong("JpgFromRawStart", 513, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD, true);
        EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD = tagInfoLong8;
        TagInfoLong tagInfoLong9 = new TagInfoLong("JpgFromRawStart", 513, TiffDirectoryType.EXIF_DIRECTORY_IFD2, true);
        EXIF_TAG_JPG_FROM_RAW_START_IFD2 = tagInfoLong9;
        TagInfoLong tagInfoLong10 = new TagInfoLong("OtherImageStart", 513, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN, true);
        EXIF_TAG_OTHER_IMAGE_START = tagInfoLong10;
        TagInfoLong tagInfoLong11 = new TagInfoLong(ExifInterface.TAG_ORF_PREVIEW_IMAGE_LENGTH, 514, TiffDirectoryType.EXIF_DIRECTORY_MAKER_NOTES);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES = tagInfoLong11;
        TagInfoLong tagInfoLong12 = new TagInfoLong("JpgFromRawLength", 514, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD = tagInfoLong12;
        TagInfoLong tagInfoLong13 = new TagInfoLong("JpgFromRawLength", 514, TiffDirectoryType.EXIF_DIRECTORY_IFD2);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2 = tagInfoLong13;
        TagInfoLong tagInfoLong14 = new TagInfoLong("OtherImageLength", 514, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OTHER_IMAGE_LENGTH = tagInfoLong14;
        TagInfoBytes tagInfoBytes = new TagInfoBytes("ApplicationNotes", 700, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_APPLICATION_NOTES = tagInfoBytes;
        TagInfoUnknowns tagInfoUnknowns = new TagInfoUnknowns("Matteing", 32995, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MATTEING = tagInfoUnknowns;
        TagInfoUnknowns tagInfoUnknowns2 = new TagInfoUnknowns("DataType", 32996, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DATA_TYPE = tagInfoUnknowns2;
        TagInfoUnknowns tagInfoUnknowns3 = new TagInfoUnknowns("ImageDepth", 32997, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_DEPTH = tagInfoUnknowns3;
        TagInfoUnknowns tagInfoUnknowns4 = new TagInfoUnknowns("TileDepth", 32998, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TILE_DEPTH = tagInfoUnknowns4;
        TagInfoUnknowns tagInfoUnknowns5 = new TagInfoUnknowns("Model2", 33405, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MODEL_2 = tagInfoUnknowns5;
        TagInfoRationals tagInfoRationals = new TagInfoRationals("ExposureTime", 33434, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_TIME = tagInfoRationals;
        TagInfoRationals tagInfoRationals2 = new TagInfoRationals("FNumber", 33437, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FNUMBER = tagInfoRationals2;
        TagInfoLong tagInfoLong15 = new TagInfoLong("IPTC-NAA", 33723, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_IPTC_NAA = tagInfoLong15;
        TagInfoShorts tagInfoShorts = new TagInfoShorts("IntergraphPacketData", 33918, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTERGRAPH_PACKET_DATA = tagInfoShorts;
        TagInfoLongs tagInfoLongs = new TagInfoLongs("IntergraphFlagRegisters", 33919, 16, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTERGRAPH_FLAG_REGISTERS = tagInfoLongs;
        TagInfoAscii tagInfoAscii4 = new TagInfoAscii("Site", 34016, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SITE = tagInfoAscii4;
        TagInfoAscii tagInfoAscii5 = new TagInfoAscii("ColorSequence", 34017, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_SEQUENCE = tagInfoAscii5;
        TagInfoAscii tagInfoAscii6 = new TagInfoAscii("IT8Header", 34018, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IT8HEADER = tagInfoAscii6;
        TagInfoShort tagInfoShort = new TagInfoShort("RasterPadding", 34019, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_RASTER_PADDING = tagInfoShort;
        TagInfoShort tagInfoShort2 = new TagInfoShort("BitsPerRunLength", 34020, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BITS_PER_RUN_LENGTH = tagInfoShort2;
        TagInfoShort tagInfoShort3 = new TagInfoShort("BitsPerExtendedRunLength", 34021, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH = tagInfoShort3;
        TagInfoBytes tagInfoBytes2 = new TagInfoBytes("ColorTable", 34022, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_TABLE = tagInfoBytes2;
        TagInfoByte tagInfoByte = new TagInfoByte("ImageColorIndicator", 34023, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_COLOR_INDICATOR = tagInfoByte;
        TagInfoByte tagInfoByte2 = new TagInfoByte("BackgroundColorIndicator", 34024, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BACKGROUND_COLOR_INDICATOR = tagInfoByte2;
        TagInfoBytes tagInfoBytes3 = new TagInfoBytes("ImageColorValue", 34025, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_COLOR_VALUE = tagInfoBytes3;
        TagInfoBytes tagInfoBytes4 = new TagInfoBytes("BackgroundColorValue", 34026, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BACKGROUND_COLOR_VALUE = tagInfoBytes4;
        TagInfoBytes tagInfoBytes5 = new TagInfoBytes("PixelIntensityRange", 34027, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PIXEL_INTENSITY_RANGE = tagInfoBytes5;
        TagInfoByte tagInfoByte3 = new TagInfoByte("TransparencyIndicator", 34028, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TRANSPARENCY_INDICATOR = tagInfoByte3;
        TagInfoAscii tagInfoAscii7 = new TagInfoAscii("ColorCharacterization", 34029, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_CHARACTERIZATION = tagInfoAscii7;
        TagInfoShortOrLong tagInfoShortOrLong = new TagInfoShortOrLong("HCUsage", 34030, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_HCUSAGE = tagInfoShortOrLong;
        TagInfoAscii tagInfoAscii8 = new TagInfoAscii("SEMInfo", 34118, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SEMINFO = tagInfoAscii8;
        TagInfoLong tagInfoLong16 = new TagInfoLong("AFCP_IPTC", 34152, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_AFCP_IPTC = tagInfoLong16;
        TagInfoLong tagInfoLong17 = new TagInfoLong("LeafData", 34310, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LEAF_DATA = tagInfoLong17;
        TagInfoBytes tagInfoBytes6 = new TagInfoBytes("PhotoshopSettings", 34377, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PHOTOSHOP_SETTINGS = tagInfoBytes6;
        TagInfoDirectory tagInfoDirectory = new TagInfoDirectory("ExifOffset", 34665, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXIF_OFFSET = tagInfoDirectory;
        TagInfoShort tagInfoShort4 = new TagInfoShort("ExposureProgram", 34850, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_PROGRAM = tagInfoShort4;
        TagInfoAscii tagInfoAscii9 = new TagInfoAscii("SpectralSensitivity", 34852, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SPECTRAL_SENSITIVITY = tagInfoAscii9;
        TagInfoDirectory tagInfoDirectory2 = new TagInfoDirectory("GPSInfo", 34853, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GPSINFO = tagInfoDirectory2;
        TagInfoShorts tagInfoShorts2 = new TagInfoShorts(ExifInterface.TAG_PHOTOGRAPHIC_SENSITIVITY, 34855, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_ISO = tagInfoShorts2;
        TagInfoUndefineds tagInfoUndefineds = new TagInfoUndefineds("Opto - Electric Conv Factor", 34856, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OPTO_ELECTRIC_CONV_FACTOR = tagInfoUndefineds;
        TagInfoLong tagInfoLong18 = new TagInfoLong("LeafSubIFD", 34954, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LEAF_SUB_IFD = tagInfoLong18;
        TagInfoUndefineds tagInfoUndefineds2 = new TagInfoUndefineds("ExifVersion", 36864, 4, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_VERSION = tagInfoUndefineds2;
        TagInfoAscii tagInfoAscii10 = new TagInfoAscii("DateTimeOriginal", 36867, 20, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DATE_TIME_ORIGINAL = tagInfoAscii10;
        TagInfoAscii tagInfoAscii11 = new TagInfoAscii("DateTimeDigitized", 36868, 20, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DATE_TIME_DIGITIZED = tagInfoAscii11;
        TagInfoUndefineds tagInfoUndefineds3 = new TagInfoUndefineds("ComponentsConfiguration", 37121, 4, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_COMPONENTS_CONFIGURATION = tagInfoUndefineds3;
        TagInfoRational tagInfoRational = new TagInfoRational("CompressedBitsPerPixel", 37122, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_COMPRESSED_BITS_PER_PIXEL = tagInfoRational;
        TagInfoSRational tagInfoSRational = new TagInfoSRational("ShutterSpeedValue", 37377, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHUTTER_SPEED_VALUE = tagInfoSRational;
        TagInfoRational tagInfoRational2 = new TagInfoRational("ApertureValue", 37378, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_APERTURE_VALUE = tagInfoRational2;
        TagInfoSRational tagInfoSRational2 = new TagInfoSRational("BrightnessValue", 37379, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_BRIGHTNESS_VALUE = tagInfoSRational2;
        TagInfoSRational tagInfoSRational3 = new TagInfoSRational("ExposureCompensation", 37380, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_COMPENSATION = tagInfoSRational3;
        TagInfoRational tagInfoRational3 = new TagInfoRational("MaxApertureValue", 37381, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MAX_APERTURE_VALUE = tagInfoRational3;
        TagInfoRationals tagInfoRationals3 = new TagInfoRationals("Subject Distance", 37382, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_DISTANCE = tagInfoRationals3;
        TagInfoShort tagInfoShort5 = new TagInfoShort("MeteringMode", 37383, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_METERING_MODE = tagInfoShort5;
        TagInfoShort tagInfoShort6 = new TagInfoShort("LightSource", 37384, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LIGHT_SOURCE = tagInfoShort6;
        TagInfoShort tagInfoShort7 = new TagInfoShort("Flash", 37385, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASH = tagInfoShort7;
        TagInfoRationals tagInfoRationals4 = new TagInfoRationals("FocalLength", 37386, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_LENGTH = tagInfoRationals4;
        TagInfoShorts tagInfoShorts3 = new TagInfoShorts("SubjectArea", 37396, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_AREA = tagInfoShorts3;
        TagInfoDouble tagInfoDouble = new TagInfoDouble("StoNits", 37439, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_STO_NITS = tagInfoDouble;
        TagInfoUndefineds tagInfoUndefineds4 = new TagInfoUndefineds(ExifInterface.TAG_MAKER_NOTE, 37500, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MAKER_NOTE = tagInfoUndefineds4;
        TagInfoGpsText tagInfoGpsText = new TagInfoGpsText("UserComment", 37510, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_USER_COMMENT = tagInfoGpsText;
        TagInfoAscii tagInfoAscii12 = new TagInfoAscii(ExifInterface.TAG_SUBSEC_TIME, 37520, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME = tagInfoAscii12;
        TagInfoAscii tagInfoAscii13 = new TagInfoAscii(ExifInterface.TAG_SUBSEC_TIME_ORIGINAL, 37521, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME_ORIGINAL = tagInfoAscii13;
        TagInfoAscii tagInfoAscii14 = new TagInfoAscii(ExifInterface.TAG_SUBSEC_TIME_DIGITIZED, 37522, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME_DIGITIZED = tagInfoAscii14;
        TagInfoUndefineds tagInfoUndefineds5 = new TagInfoUndefineds("FlashpixVersion", 40960, 4, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASHPIX_VERSION = tagInfoUndefineds5;
        TagInfoShort tagInfoShort8 = new TagInfoShort("ExifImageWidth", 40962, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_IMAGE_WIDTH = tagInfoShort8;
        TagInfoShort tagInfoShort9 = new TagInfoShort("ExifImageLength", 40963, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_IMAGE_LENGTH = tagInfoShort9;
        TagInfoAscii tagInfoAscii15 = new TagInfoAscii("RelatedSoundFile", 40964, 13, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_RELATED_SOUND_FILE = tagInfoAscii15;
        TagInfoDirectory tagInfoDirectory3 = new TagInfoDirectory("InteropOffset", 40965, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTEROP_OFFSET = tagInfoDirectory3;
        TagInfoRationals tagInfoRationals5 = new TagInfoRationals("FlashEnergy", 41483, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASH_ENERGY_EXIF_IFD = tagInfoRationals5;
        TagInfoUndefineds tagInfoUndefineds6 = new TagInfoUndefineds("SpatialFrequencyResponse", 41484, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2 = tagInfoUndefineds6;
        TagInfoUnknowns tagInfoUnknowns6 = new TagInfoUnknowns("Noise", 41485, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_NOISE_2 = tagInfoUnknowns6;
        TagInfoRational tagInfoRational4 = new TagInfoRational("FocalPlaneXResolution", 41486, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD = tagInfoRational4;
        TagInfoRational tagInfoRational5 = new TagInfoRational("FocalPlaneYResolution", 41487, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD = tagInfoRational5;
        TagInfoShort tagInfoShort10 = new TagInfoShort("FocalPlaneResolutionUnit", 41488, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD = tagInfoShort10;
        TagInfoUnknowns tagInfoUnknowns7 = new TagInfoUnknowns("ImageNumber", 41489, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_NUMBER = tagInfoUnknowns7;
        TagInfoUnknowns tagInfoUnknowns8 = new TagInfoUnknowns("SecurityClassification", 41490, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SECURITY_CLASSIFICATION = tagInfoUnknowns8;
        TagInfoUnknowns tagInfoUnknowns9 = new TagInfoUnknowns("ImageHistory", 41491, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_HISTORY = tagInfoUnknowns9;
        TagInfoShorts tagInfoShorts4 = new TagInfoShorts("SubjectLocation", 41492, 2, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_LOCATION = tagInfoShorts4;
        TagInfoRational tagInfoRational6 = new TagInfoRational("ExposureIndex", 41493, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD = tagInfoRational6;
        TagInfoUnknowns tagInfoUnknowns10 = new TagInfoUnknowns("TIFF-EPStandardID", 41494, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TIFF_EPSTANDARD_ID_2 = tagInfoUnknowns10;
        TagInfoShort tagInfoShort11 = new TagInfoShort("SensingMethod", 41495, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SENSING_METHOD_EXIF_IFD = tagInfoShort11;
        TagInfoUndefined tagInfoUndefined2 = new TagInfoUndefined("FileSource", 41728, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FILE_SOURCE = tagInfoUndefined2;
        TagInfoUndefined tagInfoUndefined3 = new TagInfoUndefined("SceneType", 41729, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SCENE_TYPE = tagInfoUndefined3;
        TagInfoUndefineds tagInfoUndefineds7 = new TagInfoUndefineds("CFAPattern", 41730, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CFAPATTERN = tagInfoUndefineds7;
        TagInfoShort tagInfoShort12 = new TagInfoShort("CustomRendered", 41985, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CUSTOM_RENDERED = tagInfoShort12;
        TagInfoShort tagInfoShort13 = new TagInfoShort("ExposureMode", 41986, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_MODE = tagInfoShort13;
        TagInfoShort tagInfoShort14 = new TagInfoShort("WhiteBalance", 41987, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_WHITE_BALANCE_1 = tagInfoShort14;
        TagInfoRational tagInfoRational7 = new TagInfoRational("DigitalZoomRatio", 41988, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DIGITAL_ZOOM_RATIO = tagInfoRational7;
        TagInfoShort tagInfoShort15 = new TagInfoShort("FocalLengthIn35mmFormat", 41989, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT = tagInfoShort15;
        TagInfoShort tagInfoShort16 = new TagInfoShort("SceneCaptureType", 41990, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SCENE_CAPTURE_TYPE = tagInfoShort16;
        TagInfoShort tagInfoShort17 = new TagInfoShort("GainControl", 41991, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_GAIN_CONTROL = tagInfoShort17;
        TagInfoShort tagInfoShort18 = new TagInfoShort("Contrast", 41992, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONTRAST_1 = tagInfoShort18;
        TagInfoShort tagInfoShort19 = new TagInfoShort("Saturation", 41993, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SATURATION_1 = tagInfoShort19;
        TagInfoShort tagInfoShort20 = new TagInfoShort("Sharpness", 41994, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHARPNESS_1 = tagInfoShort20;
        TagInfoUndefineds tagInfoUndefineds8 = new TagInfoUndefineds("DeviceSettingDescription", 41995, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DEVICE_SETTING_DESCRIPTION = tagInfoUndefineds8;
        TagInfoShort tagInfoShort21 = new TagInfoShort("SubjectDistanceRange", 41996, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_DISTANCE_RANGE = tagInfoShort21;
        TagInfoAscii tagInfoAscii16 = new TagInfoAscii("ImageUniqueID", 42016, 33, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_IMAGE_UNIQUE_ID = tagInfoAscii16;
        TagInfoAscii tagInfoAscii17 = new TagInfoAscii("CameraOwnerName", 42032, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CAMERA_OWNER_NAME = tagInfoAscii17;
        TagInfoAscii tagInfoAscii18 = new TagInfoAscii(ExifInterface.TAG_BODY_SERIAL_NUMBER, 42033, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_BODY_SERIAL_NUMBER = tagInfoAscii18;
        TagInfoRationals tagInfoRationals6 = new TagInfoRationals(ExifInterface.TAG_LENS_SPECIFICATION, 42034, 4, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LENS_SPECIFICATION = tagInfoRationals6;
        TagInfoAscii tagInfoAscii19 = new TagInfoAscii(ExifInterface.TAG_LENS_MAKE, 42035, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LENS_MAKE = tagInfoAscii19;
        TagInfoAscii tagInfoAscii20 = new TagInfoAscii(ExifInterface.TAG_LENS_MODEL, 42036, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LENS_MODEL = tagInfoAscii20;
        TagInfoAscii tagInfoAscii21 = new TagInfoAscii(ExifInterface.TAG_LENS_SERIAL_NUMBER, 42037, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LENS_SERIAL_NUMBER = tagInfoAscii21;
        TagInfoRational tagInfoRational8 = new TagInfoRational(ExifInterface.TAG_GAMMA, 42240, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_GAMMA = tagInfoRational8;
        TagInfoUnknowns tagInfoUnknowns11 = new TagInfoUnknowns("Annotations", 50255, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ANNOTATIONS = tagInfoUnknowns11;
        TagInfoUndefined tagInfoUndefined4 = new TagInfoUndefined("PrintIM", 50341, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PRINT_IM = tagInfoUndefined4;
        TagInfoSLong tagInfoSLong = new TagInfoSLong("OffsetSchema", 59933, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_OFFSET_SCHEMA = tagInfoSLong;
        TagInfoAscii tagInfoAscii22 = new TagInfoAscii("OwnerName", TiffTagConstants.COMPRESSION_VALUE_KODAK_DCR_COMPRESSED, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_OWNER_NAME = tagInfoAscii22;
        TagInfoAscii tagInfoAscii23 = new TagInfoAscii("SerialNumber", 65001, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SERIAL_NUMBER = tagInfoAscii23;
        TagInfoAscii tagInfoAscii24 = new TagInfoAscii("Lens", 65002, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LENS = tagInfoAscii24;
        TagInfoAscii tagInfoAscii25 = new TagInfoAscii("RawFile", 65100, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_RAW_FILE = tagInfoAscii25;
        TagInfoAscii tagInfoAscii26 = new TagInfoAscii("Converter", 65101, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONVERTER = tagInfoAscii26;
        TagInfoAscii tagInfoAscii27 = new TagInfoAscii("WhiteBalance", 65102, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_WHITE_BALANCE_2 = tagInfoAscii27;
        TagInfoAscii tagInfoAscii28 = new TagInfoAscii("Exposure", 65105, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE = tagInfoAscii28;
        TagInfoAscii tagInfoAscii29 = new TagInfoAscii("Shadows", 65106, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHADOWS = tagInfoAscii29;
        TagInfoAscii tagInfoAscii30 = new TagInfoAscii("Brightness", 65107, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_BRIGHTNESS = tagInfoAscii30;
        TagInfoAscii tagInfoAscii31 = new TagInfoAscii("Contrast", 65108, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONTRAST_2 = tagInfoAscii31;
        TagInfoAscii tagInfoAscii32 = new TagInfoAscii("Saturation", 65109, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SATURATION_2 = tagInfoAscii32;
        TagInfoAscii tagInfoAscii33 = new TagInfoAscii("Sharpness", 65110, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHARPNESS_2 = tagInfoAscii33;
        TagInfoAscii tagInfoAscii34 = new TagInfoAscii("Smoothness", 65111, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SMOOTHNESS = tagInfoAscii34;
        TagInfoAscii tagInfoAscii35 = new TagInfoAscii("MoireFilter", 65112, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MOIRE_FILTER = tagInfoAscii35;
        ALL_EXIF_TAGS = Collections.unmodifiableList(Arrays.asList(tagInfoAscii, tagInfoUndefined, tagInfoAscii2, tagInfoAscii3, tagInfoLong, tagInfoLong2, tagInfoLong3, tagInfoLong4, tagInfoLong5, tagInfoLong6, tagInfoLong7, tagInfoLong8, tagInfoLong9, tagInfoLong10, tagInfoLong11, tagInfoLong12, tagInfoLong13, tagInfoLong14, tagInfoBytes, tagInfoUnknowns, tagInfoUnknowns2, tagInfoUnknowns3, tagInfoUnknowns4, tagInfoUnknowns5, tagInfoRationals, tagInfoRationals2, tagInfoLong15, tagInfoShorts, tagInfoLongs, tagInfoAscii4, tagInfoAscii5, tagInfoAscii6, tagInfoShort, tagInfoShort2, tagInfoShort3, tagInfoBytes2, tagInfoByte, tagInfoByte2, tagInfoBytes3, tagInfoBytes4, tagInfoBytes5, tagInfoByte3, tagInfoAscii7, tagInfoShortOrLong, tagInfoAscii8, tagInfoLong16, tagInfoLong17, tagInfoBytes6, tagInfoDirectory, tagInfoShort4, tagInfoAscii9, tagInfoDirectory2, tagInfoShorts2, tagInfoUndefineds, tagInfoLong18, tagInfoUndefineds2, tagInfoAscii10, tagInfoAscii11, tagInfoUndefineds3, tagInfoRational, tagInfoSRational, tagInfoRational2, tagInfoSRational2, tagInfoSRational3, tagInfoRational3, tagInfoRationals3, tagInfoAscii16, tagInfoAscii17, tagInfoAscii18, tagInfoRationals6, tagInfoAscii19, tagInfoAscii20, tagInfoAscii21, tagInfoShort5, tagInfoShort6, tagInfoShort7, tagInfoRationals4, tagInfoShorts3, tagInfoDouble, tagInfoAscii12, tagInfoAscii13, tagInfoAscii14, tagInfoUndefineds5, tagInfoShort8, tagInfoShort9, tagInfoAscii15, tagInfoDirectory3, tagInfoRationals5, tagInfoUndefineds6, tagInfoUnknowns6, tagInfoRational4, tagInfoRational5, tagInfoShort10, tagInfoUnknowns7, tagInfoUnknowns8, tagInfoUnknowns9, tagInfoShorts4, tagInfoRational6, tagInfoUnknowns10, tagInfoShort11, tagInfoUndefined2, tagInfoUndefined3, tagInfoUndefineds7, tagInfoShort12, tagInfoShort13, tagInfoShort14, tagInfoRational7, tagInfoShort15, tagInfoShort16, tagInfoShort17, tagInfoShort18, tagInfoShort19, tagInfoShort20, tagInfoUndefineds8, tagInfoShort21, tagInfoAscii16, tagInfoRational8, tagInfoUnknowns11, tagInfoUndefined4, tagInfoSLong, tagInfoAscii22, tagInfoAscii23, tagInfoAscii24, tagInfoAscii25, tagInfoAscii26, tagInfoAscii27, tagInfoAscii28, tagInfoAscii29, tagInfoAscii30, tagInfoAscii31, tagInfoAscii32, tagInfoAscii33, tagInfoAscii34, tagInfoAscii35, tagInfoGpsText, tagInfoUndefineds4));
    }

    private ExifTagConstants() {
    }
}
