package org.apache.commons.imaging.formats.tiff.constants;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.apache.commons.imaging.common.BinaryConstant;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfo;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoByte;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoBytes;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoFloat;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoUndefineds;
import org.tensorflow.lite.schema.BuiltinOptions;

/* loaded from: classes2.dex */
public final class MicrosoftHdPhotoTagConstants {
    public static final List<TagInfo> ALL_MICROSOFT_HD_PHOTO_TAGS;
    public static final int ALPHA_DATA_DISCARD_VALUE_FLEXBITS_DISCARDED = 1;
    public static final int ALPHA_DATA_DISCARD_VALUE_FULL_RESOLUTION = 0;
    public static final int ALPHA_DATA_DISCARD_VALUE_HIGHPASS_AND_LOW_PASS_FREQUENCY_DATA_DISCARDED = 3;
    public static final int ALPHA_DATA_DISCARD_VALUE_HIGH_PASS_FREQUENCY_DATA_DISCARDED = 2;
    public static final TagInfoLong EXIF_TAG_ALPHA_BYTE_COUNT;
    public static final TagInfoByte EXIF_TAG_ALPHA_DATA_DISCARD;
    public static final TagInfoLong EXIF_TAG_ALPHA_OFFSET;
    public static final TagInfoFloat EXIF_TAG_HEIGHT_RESOLUTION;
    public static final TagInfoLong EXIF_TAG_IMAGE_BYTE_COUNT;
    public static final TagInfoByte EXIF_TAG_IMAGE_DATA_DISCARD;
    public static final TagInfoLong EXIF_TAG_IMAGE_HEIGHT;
    public static final TagInfoLong EXIF_TAG_IMAGE_OFFSET;
    public static final TagInfoLong EXIF_TAG_IMAGE_TYPE;
    public static final TagInfoLong EXIF_TAG_IMAGE_WIDTH;
    public static final TagInfoUndefineds EXIF_TAG_PADDING;
    public static final TagInfoBytes EXIF_TAG_PIXEL_FORMAT;
    public static final TagInfoLong EXIF_TAG_TRANSFORMATION;
    public static final TagInfoLong EXIF_TAG_UNCOMPRESSED;
    public static final TagInfoFloat EXIF_TAG_WIDTH_RESOLUTION;
    public static final int IMAGE_DATA_DISCARD_VALUE_FLEXBITS_DISCARDED = 1;
    public static final int IMAGE_DATA_DISCARD_VALUE_FULL_RESOLUTION = 0;
    public static final int IMAGE_DATA_DISCARD_VALUE_HIGHPASS_AND_LOW_PASS_FREQUENCY_DATA_DISCARDED = 3;
    public static final int IMAGE_DATA_DISCARD_VALUE_HIGH_PASS_FREQUENCY_DATA_DISCARDED = 2;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_112_BIT_6_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_112_BIT_7_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_128_BIT_7_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_128_BIT_8_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_128_BIT_PRGBA_FLOAT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_128_BIT_RGBA_FIXED_POINT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_128_BIT_RGBA_FLOAT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_128_BIT_RGB_FLOAT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_144_BIT_8_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_16_BIT_BGR555;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_16_BIT_BGR565;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_16_BIT_GRAY;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_16_BIT_GRAY_HALF;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_24_BIT_3_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_24_BIT_BGR;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_24_BIT_RGB;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_3_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_4_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_BGR;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_BGR101010;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_BGRA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_CMYK;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_GRAY_FIXED_POINT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_GRAY_FLOAT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_PBGRA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_32_BIT_RGBE;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_40_BIT_4_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_40_BIT_5_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_40_BIT_CMYK_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_48_BIT_3_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_48_BIT_5_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_48_BIT_6_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_48_BIT_RGB;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_48_BIT_RGB_FIXED_POINT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_48_BIT_RGB_HALF;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_56_BIT_6_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_56_BIT_7_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_3_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_4_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_7_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_8_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_CMYK;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_PRGBA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_RGBA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_RGBA_FIXED_POINT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_64_BIT_RGBA_HALF;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_72_BIT_8_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_80_BIT_4_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_80_BIT_5_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_80_BIT_CMYK_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_8_BIT_GRAY;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_96_BIT_5_CHANNELS_ALPHA;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_96_BIT_6_CHANNELS;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_96_BIT_RGB_FIXED_POINT;
    public static final BinaryConstant PIXEL_FORMAT_VALUE_BLACK_AND_WHITE;
    public static final int TRANSFORMATION_VALUE_HORIZONTAL_NORMAL = 0;
    public static final int TRANSFORMATION_VALUE_MIRROR_HORIZONTAL = 2;
    public static final int TRANSFORMATION_VALUE_MIRROR_HORIZONTAL_AND_ROTATE_270_CW = 6;
    public static final int TRANSFORMATION_VALUE_MIRROR_HORIZONTAL_AND_ROTATE_90_CW = 5;
    public static final int TRANSFORMATION_VALUE_MIRROR_VERTICAL = 1;
    public static final int TRANSFORMATION_VALUE_ROTATE_180 = 3;
    public static final int TRANSFORMATION_VALUE_ROTATE_270_CW = 7;
    public static final int TRANSFORMATION_VALUE_ROTATE_90_CW = 4;
    public static final int UNCOMPRESSED_VALUE_NO = 0;
    public static final int UNCOMPRESSED_VALUE_YES = 1;

    static {
        TagInfoBytes tagInfoBytes = new TagInfoBytes("PixelFormat", 48129, 16, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PIXEL_FORMAT = tagInfoBytes;
        PIXEL_FORMAT_VALUE_BLACK_AND_WHITE = createMicrosoftHdPhotoGuidEndingWith((byte) 5);
        PIXEL_FORMAT_VALUE_8_BIT_GRAY = createMicrosoftHdPhotoGuidEndingWith((byte) 8);
        PIXEL_FORMAT_VALUE_16_BIT_BGR555 = createMicrosoftHdPhotoGuidEndingWith((byte) 9);
        PIXEL_FORMAT_VALUE_16_BIT_BGR565 = createMicrosoftHdPhotoGuidEndingWith((byte) 10);
        PIXEL_FORMAT_VALUE_16_BIT_GRAY = createMicrosoftHdPhotoGuidEndingWith((byte) 11);
        PIXEL_FORMAT_VALUE_24_BIT_BGR = createMicrosoftHdPhotoGuidEndingWith((byte) 12);
        PIXEL_FORMAT_VALUE_24_BIT_RGB = createMicrosoftHdPhotoGuidEndingWith((byte) 13);
        PIXEL_FORMAT_VALUE_32_BIT_BGR = createMicrosoftHdPhotoGuidEndingWith((byte) 14);
        PIXEL_FORMAT_VALUE_32_BIT_BGRA = createMicrosoftHdPhotoGuidEndingWith((byte) 15);
        PIXEL_FORMAT_VALUE_32_BIT_PBGRA = createMicrosoftHdPhotoGuidEndingWith((byte) 16);
        PIXEL_FORMAT_VALUE_32_BIT_GRAY_FLOAT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.ReshapeOptions);
        PIXEL_FORMAT_VALUE_48_BIT_RGB_FIXED_POINT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SkipGramOptions);
        PIXEL_FORMAT_VALUE_32_BIT_BGR101010 = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SpaceToDepthOptions);
        PIXEL_FORMAT_VALUE_48_BIT_RGB = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.MulOptions);
        PIXEL_FORMAT_VALUE_64_BIT_RGBA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.PadOptions);
        PIXEL_FORMAT_VALUE_64_BIT_PRGBA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.GatherOptions);
        PIXEL_FORMAT_VALUE_96_BIT_RGB_FIXED_POINT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.BatchToSpaceNDOptions);
        PIXEL_FORMAT_VALUE_128_BIT_RGBA_FLOAT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SpaceToBatchNDOptions);
        PIXEL_FORMAT_VALUE_128_BIT_PRGBA_FLOAT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.TransposeOptions);
        PIXEL_FORMAT_VALUE_128_BIT_RGB_FLOAT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.ReducerOptions);
        PIXEL_FORMAT_VALUE_32_BIT_CMYK = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SubOptions);
        PIXEL_FORMAT_VALUE_64_BIT_RGBA_FIXED_POINT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.DivOptions);
        PIXEL_FORMAT_VALUE_128_BIT_RGBA_FIXED_POINT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SqueezeOptions);
        PIXEL_FORMAT_VALUE_64_BIT_CMYK = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SequenceRNNOptions);
        PIXEL_FORMAT_VALUE_24_BIT_3_CHANNELS = createMicrosoftHdPhotoGuidEndingWith((byte) 32);
        PIXEL_FORMAT_VALUE_32_BIT_4_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.ExpOptions);
        PIXEL_FORMAT_VALUE_40_BIT_5_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.TopKV2Options);
        PIXEL_FORMAT_VALUE_48_BIT_6_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SplitOptions);
        PIXEL_FORMAT_VALUE_56_BIT_7_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.LogSoftmaxOptions);
        PIXEL_FORMAT_VALUE_64_BIT_8_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.CastOptions);
        PIXEL_FORMAT_VALUE_48_BIT_3_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.DequantizeOptions);
        PIXEL_FORMAT_VALUE_64_BIT_4_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.MaximumMinimumOptions);
        PIXEL_FORMAT_VALUE_80_BIT_5_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.ArgMaxOptions);
        PIXEL_FORMAT_VALUE_96_BIT_6_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.LessOptions);
        PIXEL_FORMAT_VALUE_112_BIT_7_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.NegOptions);
        PIXEL_FORMAT_VALUE_128_BIT_8_CHANNELS = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.PadV2Options);
        PIXEL_FORMAT_VALUE_40_BIT_CMYK_ALPHA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.GreaterOptions);
        PIXEL_FORMAT_VALUE_80_BIT_CMYK_ALPHA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.GreaterEqualOptions);
        PIXEL_FORMAT_VALUE_32_BIT_3_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.LessEqualOptions);
        PIXEL_FORMAT_VALUE_40_BIT_4_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SelectOptions);
        PIXEL_FORMAT_VALUE_48_BIT_5_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.SliceOptions);
        PIXEL_FORMAT_VALUE_56_BIT_6_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith((byte) 49);
        PIXEL_FORMAT_VALUE_64_BIT_7_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith((byte) 50);
        PIXEL_FORMAT_VALUE_72_BIT_8_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith((byte) 51);
        PIXEL_FORMAT_VALUE_64_BIT_3_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith((byte) 52);
        PIXEL_FORMAT_VALUE_80_BIT_4_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith((byte) 53);
        PIXEL_FORMAT_VALUE_96_BIT_5_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith((byte) 54);
        PIXEL_FORMAT_VALUE_112_BIT_6_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith((byte) 55);
        PIXEL_FORMAT_VALUE_128_BIT_7_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.PowOptions);
        PIXEL_FORMAT_VALUE_144_BIT_8_CHANNELS_ALPHA = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.ArgMinOptions);
        PIXEL_FORMAT_VALUE_64_BIT_RGBA_HALF = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.FakeQuantOptions);
        PIXEL_FORMAT_VALUE_48_BIT_RGB_HALF = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.PackOptions);
        PIXEL_FORMAT_VALUE_32_BIT_RGBE = createMicrosoftHdPhotoGuidEndingWith((byte) 61);
        PIXEL_FORMAT_VALUE_16_BIT_GRAY_HALF = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.LogicalAndOptions);
        PIXEL_FORMAT_VALUE_32_BIT_GRAY_FIXED_POINT = createMicrosoftHdPhotoGuidEndingWith(BuiltinOptions.LogicalNotOptions);
        TagInfoLong tagInfoLong = new TagInfoLong("Transformation", 48130, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TRANSFORMATION = tagInfoLong;
        TagInfoLong tagInfoLong2 = new TagInfoLong("Uncompressed", 48131, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_UNCOMPRESSED = tagInfoLong2;
        TagInfoLong tagInfoLong3 = new TagInfoLong("ImageType", 48132, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_TYPE = tagInfoLong3;
        TagInfoLong tagInfoLong4 = new TagInfoLong("ImageWidth", 48256, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_WIDTH = tagInfoLong4;
        TagInfoLong tagInfoLong5 = new TagInfoLong("ImageHeight", 48257, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_HEIGHT = tagInfoLong5;
        TagInfoFloat tagInfoFloat = new TagInfoFloat("WidthResolution", 48258, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_WIDTH_RESOLUTION = tagInfoFloat;
        TagInfoFloat tagInfoFloat2 = new TagInfoFloat("HeightResolution", 48259, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_HEIGHT_RESOLUTION = tagInfoFloat2;
        TagInfoLong tagInfoLong6 = new TagInfoLong("ImageOffset", 48320, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_OFFSET = tagInfoLong6;
        TagInfoLong tagInfoLong7 = new TagInfoLong("ImageByteCount", 48321, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_BYTE_COUNT = tagInfoLong7;
        TagInfoLong tagInfoLong8 = new TagInfoLong("AlphaOffset", 48322, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ALPHA_OFFSET = tagInfoLong8;
        TagInfoLong tagInfoLong9 = new TagInfoLong("AlphaByteCount", 48323, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ALPHA_BYTE_COUNT = tagInfoLong9;
        TagInfoByte tagInfoByte = new TagInfoByte("ImageDataDiscard", 48324, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_DATA_DISCARD = tagInfoByte;
        TagInfoByte tagInfoByte2 = new TagInfoByte("AlphaDataDiscard", 48325, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ALPHA_DATA_DISCARD = tagInfoByte2;
        TagInfoUndefineds tagInfoUndefineds = new TagInfoUndefineds("Padding", 59932, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PADDING = tagInfoUndefineds;
        ALL_MICROSOFT_HD_PHOTO_TAGS = Collections.unmodifiableList(Arrays.asList(tagInfoBytes, tagInfoLong, tagInfoLong2, tagInfoLong3, tagInfoLong4, tagInfoLong5, tagInfoFloat, tagInfoFloat2, tagInfoLong6, tagInfoLong7, tagInfoLong8, tagInfoLong9, tagInfoByte, tagInfoByte2, tagInfoUndefineds));
    }

    private static BinaryConstant createMicrosoftHdPhotoGuidEndingWith(byte b) {
        return new BinaryConstant(new byte[]{BuiltinOptions.LogSoftmaxOptions, -61, -35, BuiltinOptions.VarHandleOptions, 3, BuiltinOptions.AbsOptions, -2, BuiltinOptions.LeakyReluOptions, -79, -123, 61, 119, 118, -115, -55, b});
    }

    private MicrosoftHdPhotoTagConstants() {
    }
}
