package org.bouncycastle.asn1.bc;

import androidx.exifinterface.media.ExifInterface;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* loaded from: classes2.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bc_exch;
    public static final ASN1ObjectIdentifier bc_ext;
    public static final ASN1ObjectIdentifier bc_kem;
    public static final ASN1ObjectIdentifier bc_pbe;
    public static final ASN1ObjectIdentifier bc_pbe_sha1;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha224;
    public static final ASN1ObjectIdentifier bc_pbe_sha256;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha384;
    public static final ASN1ObjectIdentifier bc_pbe_sha512;
    public static final ASN1ObjectIdentifier bc_sig;
    public static final ASN1ObjectIdentifier bike128;
    public static final ASN1ObjectIdentifier bike192;
    public static final ASN1ObjectIdentifier bike256;
    public static final ASN1ObjectIdentifier dilithium;
    public static final ASN1ObjectIdentifier dilithium2;
    public static final ASN1ObjectIdentifier dilithium2_aes;
    public static final ASN1ObjectIdentifier dilithium3;
    public static final ASN1ObjectIdentifier dilithium3_aes;
    public static final ASN1ObjectIdentifier dilithium5;
    public static final ASN1ObjectIdentifier dilithium5_aes;
    public static final ASN1ObjectIdentifier external_value;
    public static final ASN1ObjectIdentifier falcon;
    public static final ASN1ObjectIdentifier falcon_1024;
    public static final ASN1ObjectIdentifier falcon_512;
    public static final ASN1ObjectIdentifier firesaberkem128r3;
    public static final ASN1ObjectIdentifier firesaberkem192r3;
    public static final ASN1ObjectIdentifier firesaberkem256r3;
    public static final ASN1ObjectIdentifier frodokem1344aes;
    public static final ASN1ObjectIdentifier frodokem1344shake;
    public static final ASN1ObjectIdentifier frodokem640aes;
    public static final ASN1ObjectIdentifier frodokem640shake;
    public static final ASN1ObjectIdentifier frodokem976aes;
    public static final ASN1ObjectIdentifier frodokem976shake;
    public static final ASN1ObjectIdentifier hqc128;
    public static final ASN1ObjectIdentifier hqc192;
    public static final ASN1ObjectIdentifier hqc256;
    public static final ASN1ObjectIdentifier kyber1024;
    public static final ASN1ObjectIdentifier kyber1024_aes;
    public static final ASN1ObjectIdentifier kyber512;
    public static final ASN1ObjectIdentifier kyber512_aes;
    public static final ASN1ObjectIdentifier kyber768;
    public static final ASN1ObjectIdentifier kyber768_aes;
    public static final ASN1ObjectIdentifier lightsaberkem128r3;
    public static final ASN1ObjectIdentifier lightsaberkem192r3;
    public static final ASN1ObjectIdentifier lightsaberkem256r3;
    public static final ASN1ObjectIdentifier linkedCertificate;
    public static final ASN1ObjectIdentifier mceliece348864_r3;
    public static final ASN1ObjectIdentifier mceliece348864f_r3;
    public static final ASN1ObjectIdentifier mceliece460896_r3;
    public static final ASN1ObjectIdentifier mceliece460896f_r3;
    public static final ASN1ObjectIdentifier mceliece6688128_r3;
    public static final ASN1ObjectIdentifier mceliece6688128f_r3;
    public static final ASN1ObjectIdentifier mceliece6960119_r3;
    public static final ASN1ObjectIdentifier mceliece6960119f_r3;
    public static final ASN1ObjectIdentifier mceliece8192128_r3;
    public static final ASN1ObjectIdentifier mceliece8192128f_r3;
    public static final ASN1ObjectIdentifier newHope;
    public static final ASN1ObjectIdentifier ntruhps2048509;
    public static final ASN1ObjectIdentifier ntruhps2048677;
    public static final ASN1ObjectIdentifier ntruhps4096821;
    public static final ASN1ObjectIdentifier ntruhrss701;
    public static final ASN1ObjectIdentifier ntrulpr1013;
    public static final ASN1ObjectIdentifier ntrulpr1277;
    public static final ASN1ObjectIdentifier ntrulpr653;
    public static final ASN1ObjectIdentifier ntrulpr761;
    public static final ASN1ObjectIdentifier ntrulpr857;
    public static final ASN1ObjectIdentifier ntrulpr953;
    public static final ASN1ObjectIdentifier picnic;
    public static final ASN1ObjectIdentifier picnic3l1;
    public static final ASN1ObjectIdentifier picnic3l3;
    public static final ASN1ObjectIdentifier picnic3l5;
    public static final ASN1ObjectIdentifier picnic_key;
    public static final ASN1ObjectIdentifier picnic_signature;
    public static final ASN1ObjectIdentifier picnic_with_sha3_512;
    public static final ASN1ObjectIdentifier picnic_with_sha512;
    public static final ASN1ObjectIdentifier picnic_with_shake256;
    public static final ASN1ObjectIdentifier picnicl1fs;
    public static final ASN1ObjectIdentifier picnicl1full;
    public static final ASN1ObjectIdentifier picnicl1ur;
    public static final ASN1ObjectIdentifier picnicl3fs;
    public static final ASN1ObjectIdentifier picnicl3full;
    public static final ASN1ObjectIdentifier picnicl3ur;
    public static final ASN1ObjectIdentifier picnicl5fs;
    public static final ASN1ObjectIdentifier picnicl5full;
    public static final ASN1ObjectIdentifier picnicl5ur;
    public static final ASN1ObjectIdentifier pqc_kem_bike;
    public static final ASN1ObjectIdentifier pqc_kem_frodo;
    public static final ASN1ObjectIdentifier pqc_kem_hqc;
    public static final ASN1ObjectIdentifier pqc_kem_kyber;
    public static final ASN1ObjectIdentifier pqc_kem_mceliece;
    public static final ASN1ObjectIdentifier pqc_kem_ntru;
    public static final ASN1ObjectIdentifier pqc_kem_ntrulprime;
    public static final ASN1ObjectIdentifier pqc_kem_ntruprime;
    public static final ASN1ObjectIdentifier pqc_kem_saber;
    public static final ASN1ObjectIdentifier pqc_kem_sike;
    public static final ASN1ObjectIdentifier pqc_kem_sntruprime;
    public static final ASN1ObjectIdentifier qTESLA;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_size;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_speed;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_III;
    public static final ASN1ObjectIdentifier qTESLA_p_I;
    public static final ASN1ObjectIdentifier qTESLA_p_III;
    public static final ASN1ObjectIdentifier saberkem128r3;
    public static final ASN1ObjectIdentifier saberkem192r3;
    public static final ASN1ObjectIdentifier saberkem256r3;
    public static final ASN1ObjectIdentifier sikep434;
    public static final ASN1ObjectIdentifier sikep434_compressed;
    public static final ASN1ObjectIdentifier sikep503;
    public static final ASN1ObjectIdentifier sikep503_compressed;
    public static final ASN1ObjectIdentifier sikep610;
    public static final ASN1ObjectIdentifier sikep610_compressed;
    public static final ASN1ObjectIdentifier sikep751;
    public static final ASN1ObjectIdentifier sikep751_compressed;
    public static final ASN1ObjectIdentifier sntrup1013;
    public static final ASN1ObjectIdentifier sntrup1277;
    public static final ASN1ObjectIdentifier sntrup653;
    public static final ASN1ObjectIdentifier sntrup761;
    public static final ASN1ObjectIdentifier sntrup857;
    public static final ASN1ObjectIdentifier sntrup953;
    public static final ASN1ObjectIdentifier sphincs256;
    public static final ASN1ObjectIdentifier sphincs256_with_BLAKE512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA3_512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA512;
    public static final ASN1ObjectIdentifier sphincsPlus;
    public static final ASN1ObjectIdentifier sphincsPlus_haraka;
    public static final ASN1ObjectIdentifier sphincsPlus_sha_256;
    public static final ASN1ObjectIdentifier sphincsPlus_sha_512;
    public static final ASN1ObjectIdentifier sphincsPlus_shake_256;
    public static final ASN1ObjectIdentifier xmss;
    public static final ASN1ObjectIdentifier xmss_SHA256;
    public static final ASN1ObjectIdentifier xmss_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_SHA512;
    public static final ASN1ObjectIdentifier xmss_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE256;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        bc = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier branch = aSN1ObjectIdentifier.branch("1");
        bc_pbe = branch;
        ASN1ObjectIdentifier branch2 = branch.branch("1");
        bc_pbe_sha1 = branch2;
        ASN1ObjectIdentifier branch3 = branch.branch("2.1");
        bc_pbe_sha256 = branch3;
        bc_pbe_sha384 = branch.branch("2.2");
        bc_pbe_sha512 = branch.branch("2.3");
        bc_pbe_sha224 = branch.branch("2.4");
        bc_pbe_sha1_pkcs5 = branch2.branch("1");
        ASN1ObjectIdentifier branch4 = branch2.branch(ExifInterface.GPS_MEASUREMENT_2D);
        bc_pbe_sha1_pkcs12 = branch4;
        bc_pbe_sha256_pkcs5 = branch3.branch("1");
        ASN1ObjectIdentifier branch5 = branch3.branch(ExifInterface.GPS_MEASUREMENT_2D);
        bc_pbe_sha256_pkcs12 = branch5;
        bc_pbe_sha1_pkcs12_aes128_cbc = branch4.branch("1.2");
        bc_pbe_sha1_pkcs12_aes192_cbc = branch4.branch("1.22");
        bc_pbe_sha1_pkcs12_aes256_cbc = branch4.branch("1.42");
        bc_pbe_sha256_pkcs12_aes128_cbc = branch5.branch("1.2");
        bc_pbe_sha256_pkcs12_aes192_cbc = branch5.branch("1.22");
        bc_pbe_sha256_pkcs12_aes256_cbc = branch5.branch("1.42");
        ASN1ObjectIdentifier branch6 = aSN1ObjectIdentifier.branch(ExifInterface.GPS_MEASUREMENT_2D);
        bc_sig = branch6;
        ASN1ObjectIdentifier branch7 = branch6.branch("1");
        sphincs256 = branch7;
        sphincs256_with_BLAKE512 = branch7.branch("1");
        sphincs256_with_SHA512 = branch7.branch(ExifInterface.GPS_MEASUREMENT_2D);
        sphincs256_with_SHA3_512 = branch7.branch(ExifInterface.GPS_MEASUREMENT_3D);
        ASN1ObjectIdentifier branch8 = branch6.branch(ExifInterface.GPS_MEASUREMENT_2D);
        xmss = branch8;
        ASN1ObjectIdentifier branch9 = branch8.branch("1");
        xmss_SHA256ph = branch9;
        ASN1ObjectIdentifier branch10 = branch8.branch(ExifInterface.GPS_MEASUREMENT_2D);
        xmss_SHA512ph = branch10;
        ASN1ObjectIdentifier branch11 = branch8.branch(ExifInterface.GPS_MEASUREMENT_3D);
        xmss_SHAKE128ph = branch11;
        ASN1ObjectIdentifier branch12 = branch8.branch("4");
        xmss_SHAKE256ph = branch12;
        xmss_SHA256 = branch8.branch("5");
        xmss_SHA512 = branch8.branch("6");
        xmss_SHAKE128 = branch8.branch("7");
        xmss_SHAKE256 = branch8.branch("8");
        ASN1ObjectIdentifier branch13 = branch6.branch(ExifInterface.GPS_MEASUREMENT_3D);
        xmss_mt = branch13;
        ASN1ObjectIdentifier branch14 = branch13.branch("1");
        xmss_mt_SHA256ph = branch14;
        ASN1ObjectIdentifier branch15 = branch13.branch(ExifInterface.GPS_MEASUREMENT_2D);
        xmss_mt_SHA512ph = branch15;
        xmss_mt_SHAKE128ph = branch13.branch(ExifInterface.GPS_MEASUREMENT_3D);
        xmss_mt_SHAKE256ph = branch13.branch("4");
        xmss_mt_SHA256 = branch13.branch("5");
        xmss_mt_SHA512 = branch13.branch("6");
        ASN1ObjectIdentifier branch16 = branch13.branch("7");
        xmss_mt_SHAKE128 = branch16;
        ASN1ObjectIdentifier branch17 = branch13.branch("8");
        xmss_mt_SHAKE256 = branch17;
        xmss_with_SHA256 = branch9;
        xmss_with_SHA512 = branch10;
        xmss_with_SHAKE128 = branch11;
        xmss_with_SHAKE256 = branch12;
        xmss_mt_with_SHA256 = branch14;
        xmss_mt_with_SHA512 = branch15;
        xmss_mt_with_SHAKE128 = branch16;
        xmss_mt_with_SHAKE256 = branch17;
        ASN1ObjectIdentifier branch18 = branch6.branch("4");
        qTESLA = branch18;
        qTESLA_Rnd1_I = branch18.branch("1");
        qTESLA_Rnd1_III_size = branch18.branch(ExifInterface.GPS_MEASUREMENT_2D);
        qTESLA_Rnd1_III_speed = branch18.branch(ExifInterface.GPS_MEASUREMENT_3D);
        qTESLA_Rnd1_p_I = branch18.branch("4");
        qTESLA_Rnd1_p_III = branch18.branch("5");
        qTESLA_p_I = branch18.branch("11");
        qTESLA_p_III = branch18.branch("12");
        ASN1ObjectIdentifier branch19 = branch6.branch("5");
        sphincsPlus = branch19;
        sphincsPlus_shake_256 = branch19.branch("1");
        sphincsPlus_sha_256 = branch19.branch(ExifInterface.GPS_MEASUREMENT_2D);
        sphincsPlus_sha_512 = branch19.branch(ExifInterface.GPS_MEASUREMENT_3D);
        sphincsPlus_haraka = branch19.branch("4");
        ASN1ObjectIdentifier branch20 = branch6.branch("6");
        picnic = branch20;
        ASN1ObjectIdentifier branch21 = branch20.branch("1");
        picnic_key = branch21;
        picnicl1fs = branch21.branch("1");
        picnicl1ur = branch21.branch(ExifInterface.GPS_MEASUREMENT_2D);
        picnicl3fs = branch21.branch(ExifInterface.GPS_MEASUREMENT_3D);
        picnicl3ur = branch21.branch("4");
        picnicl5fs = branch21.branch("5");
        picnicl5ur = branch21.branch("6");
        picnic3l1 = branch21.branch("7");
        picnic3l3 = branch21.branch("8");
        picnic3l5 = branch21.branch("9");
        picnicl1full = branch21.branch("10");
        picnicl3full = branch21.branch("11");
        picnicl5full = branch21.branch("12");
        ASN1ObjectIdentifier branch22 = branch20.branch(ExifInterface.GPS_MEASUREMENT_2D);
        picnic_signature = branch22;
        picnic_with_sha512 = branch22.branch("1");
        picnic_with_shake256 = branch22.branch(ExifInterface.GPS_MEASUREMENT_2D);
        picnic_with_sha3_512 = branch22.branch(ExifInterface.GPS_MEASUREMENT_3D);
        falcon = branch6.branch("7");
        falcon_512 = new ASN1ObjectIdentifier("1.3.9999.3.1");
        falcon_1024 = new ASN1ObjectIdentifier("1.3.9999.3.4");
        dilithium = branch6.branch("8");
        dilithium2 = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.7.4.4");
        dilithium3 = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.7.6.5");
        dilithium5 = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.7.8.7");
        dilithium2_aes = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.4.4");
        dilithium3_aes = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.6.5");
        dilithium5_aes = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.8.7");
        ASN1ObjectIdentifier branch23 = aSN1ObjectIdentifier.branch(ExifInterface.GPS_MEASUREMENT_3D);
        bc_exch = branch23;
        newHope = branch23.branch("1");
        ASN1ObjectIdentifier branch24 = aSN1ObjectIdentifier.branch("4");
        bc_ext = branch24;
        linkedCertificate = branch24.branch("1");
        external_value = branch24.branch(ExifInterface.GPS_MEASUREMENT_2D);
        ASN1ObjectIdentifier branch25 = aSN1ObjectIdentifier.branch("5");
        bc_kem = branch25;
        ASN1ObjectIdentifier branch26 = branch25.branch("1");
        pqc_kem_mceliece = branch26;
        mceliece348864_r3 = branch26.branch("1");
        mceliece348864f_r3 = branch26.branch(ExifInterface.GPS_MEASUREMENT_2D);
        mceliece460896_r3 = branch26.branch(ExifInterface.GPS_MEASUREMENT_3D);
        mceliece460896f_r3 = branch26.branch("4");
        mceliece6688128_r3 = branch26.branch("5");
        mceliece6688128f_r3 = branch26.branch("6");
        mceliece6960119_r3 = branch26.branch("7");
        mceliece6960119f_r3 = branch26.branch("8");
        mceliece8192128_r3 = branch26.branch("9");
        mceliece8192128f_r3 = branch26.branch("10");
        ASN1ObjectIdentifier branch27 = branch25.branch(ExifInterface.GPS_MEASUREMENT_2D);
        pqc_kem_frodo = branch27;
        frodokem640aes = branch27.branch("1");
        frodokem640shake = branch27.branch(ExifInterface.GPS_MEASUREMENT_2D);
        frodokem976aes = branch27.branch(ExifInterface.GPS_MEASUREMENT_3D);
        frodokem976shake = branch27.branch("4");
        frodokem1344aes = branch27.branch("5");
        frodokem1344shake = branch27.branch("6");
        ASN1ObjectIdentifier branch28 = branch25.branch(ExifInterface.GPS_MEASUREMENT_3D);
        pqc_kem_saber = branch28;
        lightsaberkem128r3 = branch28.branch("1");
        saberkem128r3 = branch28.branch(ExifInterface.GPS_MEASUREMENT_2D);
        firesaberkem128r3 = branch28.branch(ExifInterface.GPS_MEASUREMENT_3D);
        lightsaberkem192r3 = branch28.branch("4");
        saberkem192r3 = branch28.branch("5");
        firesaberkem192r3 = branch28.branch("6");
        lightsaberkem256r3 = branch28.branch("7");
        saberkem256r3 = branch28.branch("8");
        firesaberkem256r3 = branch28.branch("9");
        ASN1ObjectIdentifier branch29 = branch25.branch("4");
        pqc_kem_sike = branch29;
        sikep434 = branch29.branch("1");
        sikep503 = branch29.branch(ExifInterface.GPS_MEASUREMENT_2D);
        sikep610 = branch29.branch(ExifInterface.GPS_MEASUREMENT_3D);
        sikep751 = branch29.branch("4");
        sikep434_compressed = branch29.branch("5");
        sikep503_compressed = branch29.branch("6");
        sikep610_compressed = branch29.branch("7");
        sikep751_compressed = branch29.branch("8");
        ASN1ObjectIdentifier branch30 = branch25.branch("5");
        pqc_kem_ntru = branch30;
        ntruhps2048509 = branch30.branch("1");
        ntruhps2048677 = branch30.branch(ExifInterface.GPS_MEASUREMENT_2D);
        ntruhps4096821 = branch30.branch(ExifInterface.GPS_MEASUREMENT_3D);
        ntruhrss701 = branch30.branch("4");
        ASN1ObjectIdentifier branch31 = branch25.branch("6");
        pqc_kem_kyber = branch31;
        kyber512 = branch31.branch("1");
        kyber768 = branch31.branch(ExifInterface.GPS_MEASUREMENT_2D);
        kyber1024 = branch31.branch(ExifInterface.GPS_MEASUREMENT_3D);
        kyber512_aes = branch31.branch("4");
        kyber768_aes = branch31.branch("5");
        kyber1024_aes = branch31.branch("6");
        ASN1ObjectIdentifier branch32 = branch25.branch("7");
        pqc_kem_ntruprime = branch32;
        ASN1ObjectIdentifier branch33 = branch32.branch("1");
        pqc_kem_ntrulprime = branch33;
        ntrulpr653 = branch33.branch("1");
        ntrulpr761 = branch33.branch(ExifInterface.GPS_MEASUREMENT_2D);
        ntrulpr857 = branch33.branch(ExifInterface.GPS_MEASUREMENT_3D);
        ntrulpr953 = branch33.branch("4");
        ntrulpr1013 = branch33.branch("5");
        ntrulpr1277 = branch33.branch("6");
        ASN1ObjectIdentifier branch34 = branch32.branch(ExifInterface.GPS_MEASUREMENT_2D);
        pqc_kem_sntruprime = branch34;
        sntrup653 = branch34.branch("1");
        sntrup761 = branch34.branch(ExifInterface.GPS_MEASUREMENT_2D);
        sntrup857 = branch34.branch(ExifInterface.GPS_MEASUREMENT_3D);
        sntrup953 = branch34.branch("4");
        sntrup1013 = branch34.branch("5");
        sntrup1277 = branch34.branch("6");
        ASN1ObjectIdentifier branch35 = branch25.branch("8");
        pqc_kem_bike = branch35;
        bike128 = branch35.branch("1");
        bike192 = branch35.branch(ExifInterface.GPS_MEASUREMENT_2D);
        bike256 = branch35.branch(ExifInterface.GPS_MEASUREMENT_3D);
        ASN1ObjectIdentifier branch36 = branch25.branch("9");
        pqc_kem_hqc = branch36;
        hqc128 = branch36.branch("1");
        hqc192 = branch36.branch(ExifInterface.GPS_MEASUREMENT_2D);
        hqc256 = branch36.branch(ExifInterface.GPS_MEASUREMENT_3D);
    }
}
